extends Node

const ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJleHBpcmVzIjoiMjAyNC0wOC0yMlQwMjoyNTozOC4zMzY5NjI0MDArMDA6MDAiLCJ1c2VyX2lkIjoiMSJ9.bBIHMSj54AQITyYSKz_815nIsmD0XcJgp3IV1pDNej8"
const URL_ROOT = "http://127.0.0.1:3005"

const CARD_CONSIDERED = 0
const CARD_NOT_CONSIDERED = 1
const CARD_CONFIRMED = 2

const BATTLE_QUEST_IDX = 0
const RIDDLE_QUEST_IDX = 1
